name: Check Career Fair Button

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run the bot script
        id: bot-run
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python career_fair_bot.py
      
      - name: Commit and push alert log
        # This step will only run if the previous steps were successful
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Log new meeting alerts"
          file_pattern: sent_alerts.log
          
      - name: List files for debugging
        # This step will only run if a previous step has failed
        if: failure()
        run: ls -la
        
      - name: Upload debug artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug_screenshot.png
            debug_page_source.html
